os: Visual Studio 2019
version: "tester-{branch}-{build}"

branches:
 except:
  - master
  - myBuild

environment:
 PY_PYTHON: 3.7-32
 my_ghUser: XLTechie
 my_repo: nvdaTests
 my_buildBranch: myBuild

install:
 - curl -fsSL --output-dir appveyor\scripts --remote-name-all "\
   https://raw.githubusercontent.com/%my_gitUser%/%my_repo%/%my_buildBranch%/appveyor/scripts/\
   {installNVDA,pushPackagingInfo,setBuildVersionVars,setSconsArgs,uploadArtifacts}.ps1"
 - curl -fsSL --output-dir appveyor\scripts\tests --remote-name-all "\
   https://raw.githubusercontent.com/%my_gitUser%/%my_repo%/%my_buildBranch%/appveyor/scripts/tests\
   {beforeTests,checkTestFailure,lintCheck,systemTests,translationCheck,unitTests}.ps1"
 - ps: appveyor\scripts\setBuildVersionVars.ps1
 #- ps: appveyor\scripts\decryptFilesForSigning.ps1
 - py -m pip install --upgrade --no-warn-script-location pip
 - git submodule update --init

build_script:
 - ps: appveyor\scripts\setSconsArgs.ps1
 - scons source %sconsArgs%
 - scons %sconsOutTargets% %sconsArgs%
 #- ps: appveyor\scripts\buildSymbolStore.ps1
 #- 7z a -tzip -r output\symbols.zip symbols\*.dl_ symbols\*.ex_ symbols\*.pd_

before_test:
 - ps: appveyor\scripts\tests\beforeTests.ps1
 - ps: appveyor\scripts\installNVDA.ps1

test_script:
 - ps: appveyor\scripts\tests\translationCheck.ps1
 - ps: appveyor\scripts\tests\unitTests.ps1
 - ps: appveyor\scripts\tests\lintCheck.ps1
 - ps: appveyor\scripts\tests\systemTests.ps1

after_test:
 - ps: appveyor\scripts\tests\checkTestFailure.ps1

artifacts:
 - path: output\*
 - path: output\*\*

on_failure:
 - ps: appveyor\scripts\uploadArtifacts.ps1

on_finish:
 - ps: appveyor\scripts\pushPackagingInfo.ps1

max_jobs: 1
